package tebd.entity;
// Generated 02/03/2020 10:02:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String endereco;
     private String email;
     private String tel;
     private String localEmprego;
     private String numeroInscricao;
     private Date dataVencimento;
     private String cartaoCredito;
     private boolean voluntario;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set autorArtigos = new HashSet(0);
     private Set revisaos = new HashSet(0);

    public Autor() {
    }

	
    public Autor(String nome, String endereco, String email, String tel, String localEmprego, String numeroInscricao, Date dataVencimento, String cartaoCredito, boolean voluntario, Date createdAt, Date updatedAt) {
        this.nome = nome;
        this.endereco = endereco;
        this.email = email;
        this.tel = tel;
        this.localEmprego = localEmprego;
        this.numeroInscricao = numeroInscricao;
        this.dataVencimento = dataVencimento;
        this.cartaoCredito = cartaoCredito;
        this.voluntario = voluntario;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Autor(String nome, String endereco, String email, String tel, String localEmprego, String numeroInscricao, Date dataVencimento, String cartaoCredito, boolean voluntario, Date createdAt, Date updatedAt, Date deletedAt, Set autorArtigos, Set revisaos) {
       this.nome = nome;
       this.endereco = endereco;
       this.email = email;
       this.tel = tel;
       this.localEmprego = localEmprego;
       this.numeroInscricao = numeroInscricao;
       this.dataVencimento = dataVencimento;
       this.cartaoCredito = cartaoCredito;
       this.voluntario = voluntario;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.autorArtigos = autorArtigos;
       this.revisaos = revisaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getLocalEmprego() {
        return this.localEmprego;
    }
    
    public void setLocalEmprego(String localEmprego) {
        this.localEmprego = localEmprego;
    }
    public String getNumeroInscricao() {
        return this.numeroInscricao;
    }
    
    public void setNumeroInscricao(String numeroInscricao) {
        this.numeroInscricao = numeroInscricao;
    }
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }
    public String getCartaoCredito() {
        return this.cartaoCredito;
    }
    
    public void setCartaoCredito(String cartaoCredito) {
        this.cartaoCredito = cartaoCredito;
    }
    public boolean isVoluntario() {
        return this.voluntario;
    }
    
    public void setVoluntario(boolean voluntario) {
        this.voluntario = voluntario;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getAutorArtigos() {
        return this.autorArtigos;
    }
    
    public void setAutorArtigos(Set autorArtigos) {
        this.autorArtigos = autorArtigos;
    }
    public Set getRevisaos() {
        return this.revisaos;
    }
    
    public void setRevisaos(Set revisaos) {
        this.revisaos = revisaos;
    }




}


