package tebd.entity;
// Generated 02/03/2020 10:02:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Revisao generated by hbm2java
 */
public class Revisao  implements java.io.Serializable {


     private Integer id;
     private Artigo artigo;
     private Autor autor;
     private int nota;
     private String comentario;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;

    public Revisao() {
    }

	
    public Revisao(Artigo artigo, Autor autor, int nota, String comentario, Date createdAt, Date updatedAt) {
        this.artigo = artigo;
        this.autor = autor;
        this.nota = nota;
        this.comentario = comentario;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Revisao(Artigo artigo, Autor autor, int nota, String comentario, Date createdAt, Date updatedAt, Date deletedAt) {
       this.artigo = artigo;
       this.autor = autor;
       this.nota = nota;
       this.comentario = comentario;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Artigo getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


